title: Bidulgi69
description: Hello! I'm a server developer.
theme: just-the-docs

url: https://bidulgi69.github.io

color_scheme: dark

aux_links:
  Github: https://github.com/bidulgi69

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.jpg"
