title: Bidulgi69
description: Hello! I'm a server developer.
theme: just-the-docs

url: https://bidulgi69.github.io

color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template